# Server configuration
server:
  port: 8090
  contextPath:

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data.mongodb:
    host: localhost
    port: 27017
    database: springboot

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      login: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

#spring.boot.admin.url: http://localhost:8080
